#是否开启定时保存玩家游玩时长数据
auto-save: true
#每隔多长时间保存一次（单位：分钟）
auto-save-period: 5
#游玩时长称号是否启用
level-enable: true
#游玩时长到达多少获得的称号（单位：分钟）
#格式：    时长: 称号
levels:
  0: 白银一级
  10: 白银二级
  20: 白银三级
  40: 白银四级
  60: 白银精英
  80: 大师级白银
  100: 黄金新星一级
  140: 黄金新星二级
  180: 黄金新星三级
  220: 大师级黄金新星
  300: 大师级守卫一级
  400: 大师级守卫二级
  500: 大师级守卫精英
  650: 杰出大师级守卫
  800: 传奇之鹰
  1500: 大师级传奇之鹰
  6000: 无上之首席大师
  10000: 全球精英
#到达对应时间后获得称号显示的颜色
#颜色代号： 白W 绿GR 蓝BL 红R 粉P 金GO
level-colours:
  80: W
  220: GO
  650: P
  10000: R